# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-user-service:
    docker:
    - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: 
          working_directory: ~/project
          name: Install
          command: |
            npm install
      - run: 
          working_directory: ~/project
          name: Test
          command: |
            npm test
      - run: 
          working_directory: ~/project
          name: Build
          command: |
            npm run build
      - slack/status:
          mentions: 'CHANNEL'
          success_message: 'Code in Project-3-userservice is ready for you to pull'
          failure_message: 'You should probably tell Tanique that the code in Project-3-userservice failed'
workflows:
    build-and-test:
      jobs:
        - build-user-service